# [manager]
# keymap = [{ on = ["g", "D"], run = "cd ~/Documentos/", desc = "Go Documentos" }]
[mgr]
append_keymap = [
  { on = [
    "g",
    "D",
  ], run = "cd ~/Documentos/", desc = "Go Documentos" },
  { on = [
    "g",
    "O",
  ], run = "cd ~/Descargas", desc = "Go Descargas" },
]
